### PR TITLE
Lock to the client stateful state

### LINKED ISSUE #18: Lock to the client in stateful case
From spiiroin

- [x] when stateful op is started, lock on to client -> cancel etc is accepted only from client who initiated the op

- [x] I guess the important bits atm: that "lock-onto-client" + every op that starts should end with: aborted, failed, or appropriate success signal 1st, then fpd going idle

- [x] so that signaling that is related to operation happens while fpd is in state that indicates that operation

To comply with it, we will have to trust local map string<->fingerprintID more and not update that on every operation:

- [x] generate map on boot/user switch and then use it with updated records. 
- [x] save map after each change, it will be checked against android store when booted next time.

### PR DESCRIPTION
**Pull request by rinigus**
This PR addresses housekeeping issues of the daemon:

- ensures that the cancel timer is called only when needed and will not cancel some operation just by chance
- loads and adjusts fingerprint id <-> fingerprint name map on start and updates it from successful additions and removals. This allows to avoid calling enroll after operations and move to idle immediately
- emit failure signals before switching to idle. that way failure is associated with the state leading to it.
- allow to cancel operations only by clients that requested particular operation.

As a result of these changes, device reboots got resolved as well (#10). Now I can add several FPs without any issues and reboots. I guess reboot was caused by something on SFOS as it was getting unexpected replied from the daemon.

Fixes #18 and #10

### CODE REVIEW

File: src/fpdcommunity.h [hunk 1]
```diff
@@ -96,13 +99,14 @@ class FPDCommunity : public QObject
...
+    Q_INVOKABLE int Identify(const QDBusMessage &message);
     Q_INVOKABLE QString GetState();
     Q_INVOKABLE QStringList GetAll(); //Returns list of templates in store
-    Q_INVOKABLE int Abort();
-    Q_INVOKABLE int Verify();
-    Q_INVOKABLE int Remove(const QString &finger);
+    Q_INVOKABLE int Abort(const QDBusMessage &message);
+    Q_INVOKABLE int Verify(const QDBusMessage &message);
+    Q_INVOKABLE int Remove(const QString &finger, const QDBusMessage &message);
+    Q_INVOKABLE void Clear(const QDBusMessage &message);
```
Comment (piggz) [inline src/fpdcommunity.h:109]: Ccan you move Clear back outside the comment block, as that signifies the expected API

Comment (piggz) [reply src/fpdcommunity.h:109]: Ill move it after merge
